In [1]:
import requests
import pandas as pd
from datetime import datetime, timezone
from sqlalchemy import create_engine, text
import json


HEADERS = {
    "User-Agent": "weather-pipeline/0.1 (bloodshard614@gmail.com)",
    "Accept": "application/geo+json"
}

def nws_get(url: str) -> dict:
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()

def latest_station_observation(station_id: str) -> dict:
    url = f"https://api.weather.gov/stations/{station_id}/observations/latest"
    data = nws_get(url)
    props = data["properties"]
    print(url)

    return {
        "station_id": station_id,
        "station_name": props.get("stationName"),
        "observed_at": props.get("timestamp"),
        "ingested_at": datetime.now(timezone.utc).isoformat(),

        "latitude": data.get("geometry", {}).get("coordinates", [None, None])[1],
        "longitude": data.get("geometry", {}).get("coordinates", [None, None])[0],
        "elevation_m": props.get("elevation", {}).get("value"),

        "temperature_c": props.get("temperature", {}).get("value"),
        "dewpoint_c": props.get("dewpoint", {}).get("value"),
        "relative_humidity_pct": props.get("relativeHumidity", {}).get("value"),

        "wind_direction_deg": props.get("windDirection", {}).get("value"),
        "wind_speed_kmh": props.get("windSpeed", {}).get("value"),
        "wind_gust_kmh": props.get("windGust", {}).get("value"),

        "barometric_pressure_pa": props.get("barometricPressure", {}).get("value"),
        "sea_level_pressure_pa": props.get("seaLevelPressure", {}).get("value"),
        "visibility_m": props.get("visibility", {}).get("value"),

        "heat_index_c": props.get("heatIndex", {}).get("value"),
        "wind_chill_c": props.get("windChill", {}).get("value"),
        "precipitation_last_3h_mm": props.get("precipitationLast3Hours", {}).get("value"),

        "text_description": props.get("textDescription"),
        "raw_message": props.get("rawMessage"),
        "cloud_layers": props.get("cloudLayers"),
        "present_weather": props.get("presentWeather"),

        "raw": data,
}

observations = []
stations = [
    "KATL",  # Atlanta
    "KLAX",  # Los Angeles
    "KORD",  # Chicago O'Hare
    "KDFW",  # Dallas/Fort Worth
    "KDEN",  # Denver
    "KJFK",  # New York JFK
    "KSFO",  # San Francisco
    "KSEA",  # Seattle-Tacoma
    "KMCO",  # Orlando
    "KMIA",  # Miami
    "KBOS",  # Boston Logan
    "KEWR",  # Newark Liberty
    "KIAD",  # Washington Dulles
    "KDCA",  # Reagan National
    "KCLT",  # Charlotte Douglas
    "KPHX",  # Phoenix Sky Harbor
    "KIAH",  # Houston Intercontinental
    "KMSP",  # Minneapolis-St. Paul
    "KDTW",  # Detroit Metro
    "KPHL",  # Philadelphia
    "KSLC",  # Salt Lake City
    "KTPA",  # Tampa
    "KSAN",  # San Diego
    "KLAS",  # Harry Reid (Las Vegas)
    "KPDX",  # Portland
    "KRDU",  # Raleigh-Durham
    "KBNA",  # Nashville
    "KAUS",  # Austin-Bergstrom
    "KBDL",  # Bradley International
    "KCLE",  # Cleveland Hopkins
    "KCVG",  # Cincinnati/Northern Kentucky
    "KPIT",  # Pittsburgh
    "KSTL",  # St. Louis Lambert
    "KMCI",  # Kansas City
    "KIND",  # Indianapolis
    "KSMF",  # Sacramento
    "KMSY",  # New Orleans
    "PANC",  # Anchorage
    "PHNL",  # Honolulu
    "TJSJ"   # San Juan, Puerto Rico
]
weather_update = pd.DataFrame(
    [latest_station_observation(station) for station in stations]
)

https://api.weather.gov/stations/KATL/observations/latest
https://api.weather.gov/stations/KLAX/observations/latest
https://api.weather.gov/stations/KORD/observations/latest
https://api.weather.gov/stations/KDFW/observations/latest
https://api.weather.gov/stations/KDEN/observations/latest
https://api.weather.gov/stations/KJFK/observations/latest
https://api.weather.gov/stations/KSFO/observations/latest
https://api.weather.gov/stations/KSEA/observations/latest
https://api.weather.gov/stations/KMCO/observations/latest
https://api.weather.gov/stations/KMIA/observations/latest
https://api.weather.gov/stations/KBOS/observations/latest
https://api.weather.gov/stations/KEWR/observations/latest
https://api.weather.gov/stations/KIAD/observations/latest
https://api.weather.gov/stations/KDCA/observations/latest
https://api.weather.gov/stations/KCLT/observations/latest
https://api.weather.gov/stations/KPHX/observations/latest
https://api.weather.gov/stations/KIAH/observations/latest
https://api.weather.gov/stations/KMSP/observations/latest
https://api.weather.gov/stations/KDTW/observations/latest
https://api.weather.gov/stations/KPHL/observations/latest
https://api.weather.gov/stations/KSLC/observations/latest
https://api.weather.gov/stations/KTPA/observations/latest
https://api.weather.gov/stations/KSAN/observations/latest
https://api.weather.gov/stations/KLAS/observations/latest
https://api.weather.gov/stations/KPDX/observations/latest
https://api.weather.gov/stations/KRDU/observations/latest
https://api.weather.gov/stations/KBNA/observations/latest
https://api.weather.gov/stations/KAUS/observations/latest
https://api.weather.gov/stations/KBDL/observations/latest
https://api.weather.gov/stations/KCLE/observations/latest
https://api.weather.gov/stations/KCVG/observations/latest
https://api.weather.gov/stations/KPIT/observations/latest
https://api.weather.gov/stations/KSTL/observations/latest
https://api.weather.gov/stations/KMCI/observations/latest
https://api.weather.gov/stations/KIND/observations/latest
https://api.weather.gov/stations/KSMF/observations/latest
https://api.weather.gov/stations/KMSY/observations/latest
https://api.weather.gov/stations/PANC/observations/latest
https://api.weather.gov/stations/PHNL/observations/latest
https://api.weather.gov/stations/TJSJ/observations/latest

In [2]:
weather_update

,station_id,station_name,observed_at,ingested_at,latitude,longitude,elevation_m,temperature_c,dewpoint_c,relative_humidity_pct,...,sea_level_pressure_pa,visibility_m,heat_index_c,wind_chill_c,precipitation_last_3h_mm,text_description,raw_message,cloud_layers,present_weather,raw
0,KATL,"Atlanta, Hartsfield - Jackson Atlanta Internat...",2026-07-13T14:20:00+00:00,2026-07-13T14:38:56.802128+00:00,33.65,-84.42,315,25.0,22.0,83.452627,...,NaN,14484.10,25.734596,None,None,Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 4...",[],{'@context': ['https://geojson.org/geojson-ld/...
1,KLAX,"Los Angeles, Los Angeles International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:38:57.125940+00:00,33.93,-118.40,32,21.0,17.0,77.915158,...,NaN,14484.10,NaN,None,None,Partly Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
2,KORD,"Chicago, Chicago-O'Hare International Airport",2026-07-13T14:20:00+00:00,2026-07-13T14:38:57.463274+00:00,41.98,-87.90,205,27.0,19.0,61.613747,...,NaN,16093.44,28.198670,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
3,KDFW,Dallas/Fort Worth International Airport,2026-07-13T14:20:00+00:00,2026-07-13T14:38:57.790204+00:00,32.90,-97.03,182,24.0,22.0,88.599353,...,NaN,16093.44,24.768983,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
4,KDEN,"Denver, Denver International Airport",2026-07-13T13:53:00+00:00,2026-07-13T14:38:58.132824+00:00,39.86,-104.67,1656,25.0,12.8,46.669625,...,101450.0,16090.00,24.774151,None,None,Mostly Clear and Windy,KDEN 131353Z 16017KT 10SM FEW120 25/13 A3024 R...,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
5,KJFK,"New York, Kennedy International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:38:58.468517+00:00,40.65,-73.78,7,25.0,18.0,65.145510,...,NaN,16093.44,25.256577,None,None,Partly Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
6,KSFO,"San Francisco, San Francisco International Air...",2026-07-13T14:25:00+00:00,2026-07-13T14:38:58.807409+00:00,37.62,-122.38,5,17.0,13.0,77.310000,...,NaN,16093.44,NaN,None,None,,,[],[],{'@context': ['https://geojson.org/geojson-ld/...
7,KSEA,"Seattle, Seattle-Tacoma International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:38:59.135026+00:00,47.45,-122.30,137,15.0,8.0,62.946377,...,NaN,16093.44,NaN,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
8,KMCO,Orlando International Airport,2026-07-13T13:53:00+00:00,2026-07-13T14:38:59.453906+00:00,28.43,-81.31,32,29.0,23.0,70.108742,...,NaN,16090.00,32.747453,None,None,Mostly Cloudy,KMCO 131353Z 25004KT 10SM BKN160 BKN250 29/23 ...,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 4...",[],{'@context': ['https://geojson.org/geojson-ld/...
9,KMIA,"Miami, Miami International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:38:59.818294+00:00,25.82,-80.28,4,32.0,25.0,66.582191,...,NaN,16093.44,39.199205,None,None,Mostly Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 8...",[],{'@context': ['https://geojson.org/geojson-ld/...
10,KBOS,"Boston, Logan International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:39:00.177338+00:00,42.36,-71.01,70,28.0,NaN,NaN,...,NaN,16093.44,NaN,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
11,KEWR,"Newark, Newark International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:39:00.501531+00:00,40.70,-74.17,9,26.0,14.0,47.553680,...,NaN,16093.44,25.897235,None,None,Mostly Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
12,KIAD,"Washington/Dulles International Airport, DC",2026-07-13T14:25:00+00:00,2026-07-13T14:39:00.844818+00:00,38.95,-77.45,98,26.0,17.0,57.634333,...,NaN,16093.44,26.160452,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
13,KDCA,"Washington/Reagan National Airport, DC",2026-07-13T14:25:00+00:00,2026-07-13T14:39:01.162337+00:00,38.85,-77.03,20,27.0,16.0,50.986772,...,NaN,16093.44,27.477668,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
14,KCLT,Charlotte/Douglas International Airport,2026-07-13T14:25:00+00:00,2026-07-13T14:39:01.474746+00:00,35.22,-80.93,234,23.0,22.0,94.105818,...,NaN,16093.44,23.812763,None,None,Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 2...",[],{'@context': ['https://geojson.org/geojson-ld/...
15,KPHX,"Phoenix, Phoenix Sky Harbor International Airport",2026-07-13T14:15:00+00:00,2026-07-13T14:39:01.806682+00:00,33.43,-112.02,337,30.0,19.0,51.758801,...,NaN,16093.44,31.332008,None,None,Mostly Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 2...",[],{'@context': ['https://geojson.org/geojson-ld/...
16,KIAH,Houston Intercontinental Airport,2026-07-13T14:20:00+00:00,2026-07-13T14:39:02.137839+00:00,29.97,-95.35,33,29.0,26.0,83.896910,...,NaN,16093.44,35.612921,None,None,Mostly Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 4...",[],{'@context': ['https://geojson.org/geojson-ld/...
17,KMSP,"Minneapolis, Minneapolis-St. Paul Internationa...",2026-07-13T14:20:00+00:00,2026-07-13T14:39:02.490610+00:00,44.88,-93.22,255,27.0,19.0,61.613747,...,NaN,16093.44,28.198670,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
18,KDTW,"Detroit, Detroit Metropolitan Wayne County Air...",2026-07-13T14:20:00+00:00,2026-07-13T14:39:02.830394+00:00,42.23,-83.33,202,27.0,14.0,44.830942,...,NaN,16093.44,27.116975,None,None,Mostly Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 2...",[],{'@context': ['https://geojson.org/geojson-ld/...
19,KPHL,"Philadelphia, Philadelphia International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:39:03.225814+00:00,39.87,-75.25,6,26.0,18.0,61.388520,...,NaN,16093.44,26.258478,None,None,Mostly Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 1...",[],{'@context': ['https://geojson.org/geojson-ld/...
20,KSLC,"Salt Lake City, Salt Lake City International A...",2026-07-13T14:20:00+00:00,2026-07-13T14:39:03.567110+00:00,40.78,-111.97,1288,28.0,7.0,26.518080,...,NaN,16093.44,26.948135,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
21,KTPA,"Tampa, Tampa International Airport",2026-07-13T14:20:00+00:00,2026-07-13T14:39:03.877358+00:00,27.97,-82.53,3,31.0,26.0,74.788956,...,NaN,16093.44,39.102806,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
22,KSAN,San Diego International Airport,2026-07-13T14:20:00+00:00,2026-07-13T14:39:04.209880+00:00,32.73,-117.17,9,21.0,18.0,82.990399,...,NaN,16093.44,NaN,None,None,Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
23,KLAS,Harry Reid International Airport,2026-07-13T14:20:00+00:00,2026-07-13T14:39:04.544078+00:00,36.08,-115.17,664,33.0,11.0,26.083575,...,NaN,16093.44,31.498404,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
24,KPDX,"Portland, Portland International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:39:04.877987+00:00,45.60,-122.60,12,14.0,10.0,76.840593,...,NaN,NaN,NaN,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
25,KRDU,"Raleigh / Durham, Raleigh-Durham International...",2026-07-13T14:25:00+00:00,2026-07-13T14:39:05.207843+00:00,35.88,-78.79,133,23.0,21.0,88.518308,...,NaN,16093.44,23.666867,None,None,Light Rain,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...","[{'intensity': 'light', 'modifier': None, 'wea...",{'@context': ['https://geojson.org/geojson-ld/...
26,KBNA,"Nashville, Nashville International Airport",2026-07-13T14:20:00+00:00,2026-07-13T14:39:05.532720+00:00,36.13,-86.68,180,25.0,21.0,78.497647,...,NaN,16093.44,25.605216,None,None,Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
27,KAUS,Austin-Bergstrom International Airport,2026-07-13T14:20:00+00:00,2026-07-13T14:39:05.875026+00:00,30.19,-97.67,165,28.0,25.0,83.787472,...,NaN,16093.44,32.698057,None,None,Cloudy,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
28,KBDL,"Windsor Locks, Bradley International Airport",2026-07-13T14:25:00+00:00,2026-07-13T14:39:06.226995+00:00,41.93,-72.68,60,27.0,17.0,54.334416,...,NaN,16093.44,27.691359,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
29,KCLE,Cleveland Hopkins International Airport,2026-07-13T14:20:00+00:00,2026-07-13T14:39:06.566007+00:00,41.42,-81.85,241,26.0,16.0,54.083374,...,NaN,16093.44,26.067733,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
30,KCVG,Cincinnati/Northern Kentucky International Air...,2026-07-13T14:20:00+00:00,2026-07-13T14:39:06.895955+00:00,39.05,-84.67,267,26.0,19.0,65.355762,...,NaN,16093.44,26.362067,None,None,Mostly Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 7...",[],{'@context': ['https://geojson.org/geojson-ld/...
31,KPIT,Pittsburgh International Airport,2026-07-13T14:25:00+00:00,2026-07-13T14:39:07.217278+00:00,40.50,-80.22,373,26.0,19.0,65.355762,...,NaN,16093.44,26.362067,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
32,KSTL,St. Louis Lambert International Airport,2026-07-13T14:20:00+00:00,2026-07-13T14:39:07.545680+00:00,38.75,-90.37,172,27.0,18.0,57.873653,...,NaN,16093.44,27.930717,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
33,KMCI,"Kansas City, Kansas City International Airport",2026-07-13T14:20:00+00:00,2026-07-13T14:39:07.875807+00:00,39.32,-94.72,312,26.0,19.0,65.355762,...,NaN,16093.44,26.362067,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
34,KIND,Indianapolis International Airport,2026-07-13T14:15:00+00:00,2026-07-13T14:39:08.201574+00:00,39.73,-86.27,246,26.0,13.0,44.557103,...,NaN,16093.44,25.818991,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
35,KSMF,Sacramento International Airport,2026-07-13T14:25:00+00:00,2026-07-13T14:39:08.523015+00:00,38.70,-121.58,7,24.0,17.0,64.933548,...,NaN,16093.44,24.151043,None,None,Clear,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 3...",[],{'@context': ['https://geojson.org/geojson-ld/...
36,KMSY,"New Orleans, New Orleans International Airport",2026-07-13T14:20:00+00:00,2026-07-13T14:39:08.841567+00:00,29.98,-90.25,9,24.0,23.0,94.148645,...,NaN,6437.38,24.913881,None,None,Rain and Fog/Mist,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 9...","[{'intensity': None, 'modifier': None, 'weathe...",{'@context': ['https://geojson.org/geojson-ld/...
37,PANC,"Anchorage, Ted Stevens Anchorage International...",2026-07-13T14:25:00+00:00,2026-07-13T14:39:09.200178+00:00,61.17,-150.02,40,11.0,10.0,93.553472,...,NaN,14484.10,NaN,None,None,Light Rain,,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 1...","[{'intensity': 'light', 'modifier': None, 'wea...",{'@context': ['https://geojson.org/geojson-ld/...
38,PHNL,Daniel K Inouye International Airport,2026-07-13T13:53:00+00:00,2026-07-13T14:39:09.604418+00:00,21.35,-157.93,5,25.6,18.9,66.507319,...,101550.0,16090.00,25.952136,None,None,Partly Cloudy,PHNL 131353Z 06008KT 10SM FEW023 SCT033 SCT042...,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 7...",[],{'@context': ['https://geojson.org/geojson-ld/...
39,TJSJ,"San Juan, Luis Munoz Marin International Airport",2026-07-13T13:56:00+00:00,2026-07-13T14:39:09.971381+00:00,18.43,-66.00,19,30.0,23.3,67.391164,...,101880.0,12870.00,34.421727,None,None,Partly Cloudy,TJSJ 131356Z 10010G18KT 8SM FEW028 SCT038 SCT0...,"[{'base': {'unitCode': 'wmoUnit:m', 'value': 8...",[],{'@context': ['https://geojson.org/geojson-ld/...

In [3]:
from sqlalchemy import create_engine, text
import json

json_cols = ["raw", "cloud_layers", "present_weather"]

for col in json_cols:
    weather_update[col] = weather_update[col].apply(
        lambda x: json.dumps(x) if isinstance(x, (dict, list)) else x
    )

engine = create_engine(
    "postgresql+psycopg2://postgres:password@localhost:5432/postgres"
)

with engine.connect() as connection:
    result = connection.execute(text("SELECT current_database(), current_user;"))
    print(result.fetchone())

    existing_records = pd.read_sql(
        """
        SELECT station_id, observed_at
        FROM public.weather_update
        """,
        con=connection
    )

weather_update = weather_update.merge(
    existing_records,
    on=["station_id", "observed_at"],
    how="left",
    indicator=True
)

weather_update = weather_update[weather_update["_merge"] == "left_only"]
weather_update = weather_update.drop(columns=["_merge"])

if len(weather_update) > 0:
    weather_update.to_sql(
        name="weather_update",
        con=engine,
        schema="public",
        if_exists="append",
        index=False,
        method="multi",
        chunksize=1000
    )
    print(f"inserted rows: {len(weather_update)}")
else:
    print("no new records to insert")

('postgres', 'postgres')
inserted rows: 40

In [4]:
Weather_Data_Query = """SELECT * FROM public.weather_update;"""

with engine.connect() as conn:
    Weather_Data = pd.read_sql(Weather_Data_Query, conn)

Weather_Data

,station_id,station_name,observed_at,ingested_at,latitude,longitude,elevation_m,temperature_c,dewpoint_c,relative_humidity_pct,...,sea_level_pressure_pa,visibility_m,heat_index_c,wind_chill_c,precipitation_last_3h_mm,text_description,raw_message,cloud_layers,present_weather,raw
0,KBDL,"Windsor Locks, Bradley International Airport",2026-07-09T17:25:00+00:00,2026-07-09T17:45:00.009024+00:00,41.93,-72.68,60,32.0,21.0,52.265454,...,None,16093.44,34.923051,None,None,Mostly Clear,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 3...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."
1,KBDL,"Windsor Locks, Bradley International Airport",2026-07-09T17:30:00+00:00,2026-07-09T17:59:31.792680+00:00,41.93,-72.68,60,32.0,20.0,49.139330,...,None,16093.44,34.159568,None,None,Mostly Clear,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 1...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."
2,KBDL,"Windsor Locks, Bradley International Airport",2026-07-09T17:40:00+00:00,2026-07-09T18:08:47.302827+00:00,41.93,-72.68,60,31.0,20.0,52.012926,...,None,16093.44,33.023501,None,None,Partly Cloudy,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 1...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."
3,KBOS,"Boston, Logan International Airport",2026-07-09T17:50:00+00:00,2026-07-09T18:13:15.111881+00:00,42.36,-71.01,70,33.0,16.0,36.117357,...,None,16093.44,33.004716,None,None,Mostly Clear,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 1...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."
4,KBDL,"Windsor Locks, Bradley International Airport",2026-07-09T17:50:00+00:00,2026-07-09T18:17:01.435763+00:00,41.93,-72.68,60,32.0,20.0,49.139330,...,None,16093.44,34.159568,None,None,Partly Cloudy,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 1...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,KSMF,Sacramento International Airport,2026-07-13T14:25:00+00:00,2026-07-13T14:39:08.523015+00:00,38.70,-121.58,7,24.0,17.0,64.933548,...,None,16093.44,24.151043,None,None,Clear,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 3...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."
290,KMSY,"New Orleans, New Orleans International Airport",2026-07-13T14:20:00+00:00,2026-07-13T14:39:08.841567+00:00,29.98,-90.25,9,24.0,23.0,94.148645,...,None,6437.38,24.913881,None,None,Rain and Fog/Mist,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 9...","[{""intensity"": null, ""modifier"": null, ""weathe...","{""@context"": [""https://geojson.org/geojson-ld/..."
291,PANC,"Anchorage, Ted Stevens Anchorage International...",2026-07-13T14:25:00+00:00,2026-07-13T14:39:09.200178+00:00,61.17,-150.02,40,11.0,10.0,93.553472,...,None,14484.10,NaN,None,None,Light Rain,,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 1...","[{""intensity"": ""light"", ""modifier"": null, ""wea...","{""@context"": [""https://geojson.org/geojson-ld/..."
292,PHNL,Daniel K Inouye International Airport,2026-07-13T13:53:00+00:00,2026-07-13T14:39:09.604418+00:00,21.35,-157.93,5,26.0,19.0,66.507319,...,101550.0,16090.00,25.952136,None,None,Partly Cloudy,PHNL 131353Z 06008KT 10SM FEW023 SCT033 SCT042...,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 7...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."
293,TJSJ,"San Juan, Luis Munoz Marin International Airport",2026-07-13T13:56:00+00:00,2026-07-13T14:39:09.971381+00:00,18.43,-66.00,19,30.0,23.0,67.391164,...,101880.0,12870.00,34.421727,None,None,Partly Cloudy,TJSJ 131356Z 10010G18KT 8SM FEW028 SCT038 SCT0...,"[{""base"": {""unitCode"": ""wmoUnit:m"", ""value"": 8...",[],"{""@context"": [""https://geojson.org/geojson-ld/..."

In [5]:
query = """
SELECT table_schema,
       table_name
FROM information_schema.tables
WHERE table_type='BASE TABLE'
ORDER BY table_schema, table_name;
"""

with engine.connect() as conn:
    df = pd.read_sql(query, conn)

df

          table_schema               table_name
0   information_schema             sql_features
1   information_schema  sql_implementation_info
2   information_schema                sql_parts
3   information_schema               sql_sizing
4           pg_catalog             pg_aggregate
..                 ...                      ...
73             pgagent              pga_jobstep
74             pgagent           pga_jobsteplog
75             pgagent             pga_schedule
76              public           Weather_Update
77              public           weather_update

[78 rows x 2 columns]

In [6]:
with engine.connect() as conn:
    tables = conn.execute(text("""
        SELECT table_schema, table_name
        FROM information_schema.tables
        WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
        ORDER BY table_schema, table_name;
    """)).fetchall()

    for table in tables:
        print(table)

('pgagent', 'pga_exception')
('pgagent', 'pga_job')
('pgagent', 'pga_jobagent')
('pgagent', 'pga_jobclass')
('pgagent', 'pga_joblog')
('pgagent', 'pga_jobstep')
('pgagent', 'pga_jobsteplog')
('pgagent', 'pga_schedule')
('public', 'Weather_Update')
('public', 'weather_update')

In [7]:
from sqlalchemy import create_engine, text

admin_engine = create_engine(
    "postgresql+psycopg2://postgres:password@localhost:5432/postgres"
)

with admin_engine.connect() as conn:
    dbs = conn.execute(text("""
        SELECT datname
        FROM pg_database
        WHERE datistemplate = false
        ORDER BY datname;
    """)).fetchall()

    for db in dbs:
        print(db[0])

Daycare Fraud
Finances
Weather Data
postgres

In [8]:
with admin_engine.connect() as conn:
    rows = conn.execute(text('SELECT COUNT(*) FROM public."Weather_Update";')).scalar()
    print(rows)

5